version: '3'

services:
  follow_up:
    build: .
    env_file:
      - .env
    command: python main.py
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./infra/certs:/etc/nginx/certs
    networks:
      - app-network
    depends_on:
      - follow_up

networks:
  app-network:
    driver: bridge
