version: '3'

services:
  app-follow_up:
    build: .
    container_name: app_follow-up
    env_file:
          - .env
    command: python main.py
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - alembic
    networks:
      - app-network
   
    
  alembic:
    build: .
    container_name: alembic-follow-up
    env_file:
      - .env
    command: alembic upgrade head
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge