version: '3'

services:
  app-follow_up:
    build: .
    container_name: app_follow-up
    env_file:
      - .env
    command: python main.py
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - alembic
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker-compose/certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network    

  webserver:
    image: nginx:alpine
    container_name: webserver_follow_up
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ./docker-compose/certs:/etc/nginx/certs
    networks:
      - app-network
    depends_on:
      - app-follow_up
      - certbot

  alembic:
    build: .
    container_name: alembic
    env_file:
      - .env
    command: alembic upgrade head
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    networks:
      - app-network

 

networks:
  app-network:
    driver: bridge
