"""company fields update

Revision ID: 10aa361360ce
Revises: ff98aa5609a3
Create Date: 2025-01-27 23:02:38.334166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa361360ce'
down_revision = 'ff98aa5609a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('social_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('fantasy_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('district', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('iss_retained', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('licences_n', sa.Integer(), nullable=True))
    op.drop_column('companies', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('companies', 'licences_n')
    op.drop_column('companies', 'iss_retained')
    op.drop_column('companies', 'district')
    op.drop_column('companies', 'fantasy_name')
    op.drop_column('companies', 'social_name')
    # ### end Alembic commands ###
