"""nullable for specialty in instructor, avatar in responsable

Revision ID: 1231d9de2225
Revises: 5ac47de2ac50
Create Date: 2023-08-21 21:28:59.513333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1231d9de2225'
down_revision = '5ac47de2ac50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_responsibles', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.alter_column('instructors', 'specialty_instructor_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructors', 'specialty_instructor_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('contract_responsibles', 'avatar')
    # ### end Alembic commands ###
