"""fix tables instructor payments

Revision ID: 206b2e1d2309
Revises: ee7839117719
Create Date: 2024-09-21 03:41:06.136651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '206b2e1d2309'
down_revision = 'ee7839117719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_payment_details',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bank_number', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('instructor_pix_keys')
    op.drop_table('instructor_bank_accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_bank_accounts',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('instructor_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('bank_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_digit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name='instructor_bank_accounts_instructor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='instructor_bank_accounts_pkey')
    )
    op.create_table('instructor_pix_keys',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('instructor_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name='instructor_pix_keys_instructor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='instructor_pix_keys_pkey')
    )
    op.drop_table('instructor_payment_details')
    # ### end Alembic commands ###
