"""specialty in intructors

Revision ID: 25820c7e2266
Revises: 36eafa4df099
Create Date: 2024-09-14 23:48:05.387302

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25820c7e2266'
down_revision = '36eafa4df099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_bank_accounts',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('instructor_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('bank_number', sa.Integer(), nullable=False),
    sa.Column('bank', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_digit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructor_pix_keys',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('instructor_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    typepaymentenum_ = postgresql.ENUM('PIX', 'TRANSFER', name='typepaymentenum', create_type=False)
    typepaymentenum_.create(op.get_bind(), checkfirst=True)
    
    modepaymentenum_ = postgresql.ENUM('MOUNTH', 'WEEK', 'DAY', 'HOUR', name='modepaymentenum', create_type=False)
    modepaymentenum_.create(op.get_bind(), checkfirst=True)

    op.add_column('instructors', sa.Column('specialty_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.add_column('instructors', sa.Column('type_payment', typepaymentenum_, nullable=True))
    op.add_column('instructors', sa.Column('mode_payment', modepaymentenum_, nullable=True))
    op.add_column('instructors', sa.Column('value', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'instructors', 'specialties', ['specialty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'value')
    op.drop_column('instructors', 'mode_payment')
    op.drop_column('instructors', 'type_payment')
    op.drop_column('instructors', 'specialty_id')
    op.drop_table('instructor_pix_keys')
    op.drop_table('instructor_bank_accounts')
    # ### end Alembic commands ###
