"""normaliza bank table

Revision ID: 2a009cae236a
Revises: 25820c7e2266
Create Date: 2024-09-17 02:18:41.639353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a009cae236a'
down_revision = '25820c7e2266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructor_bank_accounts', 'bank_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instructor_bank_accounts', 'bank',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('instructor_bank_accounts', 'account_digit',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instructor_bank_accounts', 'account_digit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instructor_bank_accounts', 'bank',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('instructor_bank_accounts', 'bank_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
