"""help type in execution

Revision ID: b71fe18a1499
Revises: f4bcce4d52c5
Create Date: 2023-10-22 12:06:55.118104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71fe18a1499'
down_revision = 'f4bcce4d52c5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('help_type', sa.Enum('DEPENDENT', 'INDEPENDENT', name='helptypeexecution'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'help_type')
    # ### end Alembic commands ###
