"""executions tables

Revision ID: 3081a9e3ef44
Revises: ffaff8dcf4f1
Create Date: 2023-09-17 20:58:56.278406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '3081a9e3ef44'
down_revision = 'ffaff8dcf4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('schedule_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('procedure_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('trie', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('results')
    op.alter_column('contract_address', 'responsible_contract_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_address', 'responsible_contract_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_table('results',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('procedure_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points_made', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('anotations', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_finish', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name='results_instructor_id_fkey'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='results_procedure_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='results_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.drop_table('executions')
    # ### end Alembic commands ###
