"""create type billing in contracts

Revision ID: 30e949f9cd62
Revises: 3e617fff3033
Create Date: 2024-10-16 01:56:18.621815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30e949f9cd62'
down_revision = '3e617fff3033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('type_billing', sa.Enum('PERSONAL', 'PLAN', name='categoryenum'), nullable=True))
    op.drop_column('contractors', 'mode_billing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('mode_billing', postgresql.ENUM('OPEN', 'CONFIRMED', 'DONE', name='billingenum'), autoincrement=False, nullable=True))
    op.drop_column('contractors', 'type_billing')
    # ### end Alembic commands ###
