"""instructor forgetkey

Revision ID: 459919936310
Revises: 206b2e1d2309
Create Date: 2024-09-21 03:45:15.727216

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '459919936310'
down_revision = '206b2e1d2309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor_payment_details', sa.Column('instructor_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.alter_column('instructor_payment_details', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('instructor_payment_details', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'instructor_payment_details', 'instructors', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructor_payment_details', type_='foreignkey')
    op.alter_column('instructor_payment_details', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('instructor_payment_details', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('instructor_payment_details', 'instructor_id')
    # ### end Alembic commands ###
