"""refresh tables -students

Revision ID: 57056d40a928
Revises: 1332d53b9412
Create Date: 2023-08-13 00:32:21.737632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57056d40a928'
down_revision = '1332d53b9412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('allergy', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'allergy')
    # ### end Alembic commands ###
