"""events table create, title

Revision ID: 5ac47de2ac50
Revises: 771f349e3d1c
Create Date: 2023-08-18 22:05:45.092661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ac47de2ac50'
down_revision = '771f349e3d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(length=20), nullable=False))
    op.alter_column('events', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
