"""executions table user_id

Revision ID: 6329cbf5f6f9
Revises: 3081a9e3ef44
Create Date: 2023-09-17 21:10:24.556384

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6329cbf5f6f9'
down_revision = '3081a9e3ef44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
    op.alter_column('executions', 'trie',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('executions', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'executions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.alter_column('executions', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('executions', 'trie',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('executions', 'user_id')
    # ### end Alembic commands ###
