"""add crp in instructors table

Revision ID: 6fb88ab8fe62
Revises: b93effe1644d
Create Date: 2025-04-09 22:34:29.020276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb88ab8fe62'
down_revision = 'b93effe1644d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('crp', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'crp')
    # ### end Alembic commands ###
