"""delete colunm

Revision ID: 70ab89964589
Revises: f96228a0f9e0
Create Date: 2024-01-24 00:55:00.633598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ab89964589'
down_revision = 'f96228a0f9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
