"""normalize tables

Revision ID: 75ce17a5c82b
Revises: e98f8c0bd129
Create Date: 2025-03-10 23:32:18.439842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75ce17a5c82b'
down_revision = 'e98f8c0bd129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_plans', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('health_plans', sa.Column('district', sa.String(length=50), nullable=True))
    op.drop_column('health_plans', 'number_address')
    op.alter_column('invoices', 'sender_status',
               existing_type=postgresql.ENUM('SENDER', 'CANCELED', name='invoicesenderstatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'sender_status',
               existing_type=postgresql.ENUM('SENDER', 'CANCELED', name='invoicesenderstatusenum'),
               nullable=True)
    op.add_column('health_plans', sa.Column('number_address', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('health_plans', 'district')
    op.drop_column('health_plans', 'number')
    # ### end Alembic commands ###
