"""events table create

Revision ID: 771f349e3d1c
Revises: 61b85329975e
Create Date: 2023-08-18 00:34:01.561288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '771f349e3d1c'
down_revision = '61b85329975e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('company_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('event_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('skill_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('student_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('instructor_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'PAUSED', 'CANCELED', 'DONE', name='statusevents'), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('grids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grids',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('skill_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_schedule', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_preview', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('observation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_finish', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'PAUSED', 'CANCELED', 'DONE', name='statusgrid'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], name='grids_instructor_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='grids_skill_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='grids_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grids_pkey')
    )
    op.drop_table('events')
    # ### end Alembic commands ###
