"""fix forget key in executions

Revision ID: aab8897a6ade
Revises: a8c4dfed1d43
Create Date: 2024-07-10 00:22:13.117629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab8897a6ade'
down_revision = 'a8c4dfed1d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('executions_procedure_schedule_id_fkey', 'executions', type_='foreignkey')
    op.create_foreign_key(None, 'executions', 'procedures_schedueles', ['procedure_schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.create_foreign_key('executions_procedure_schedule_id_fkey', 'executions', 'procedures', ['procedure_schedule_id'], ['id'])
    # ### end Alembic commands ###
