"""add title colunm

Revision ID: aeda2fe22407
Revises: 70ab89964589
Create Date: 2024-01-24 00:55:41.806808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeda2fe22407'
down_revision = '70ab89964589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'title')
    # ### end Alembic commands ###
