"""normalize database versions

Revision ID: af6fe76699ee
Revises: aab8897a6ade
Create Date: 2024-08-01 01:44:49.727962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af6fe76699ee'
down_revision = 'aab8897a6ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('number_address', sa.Integer(), nullable=True))
    op.alter_column('executions', 'procedure_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executions', 'procedure_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('companies', 'number_address')
    # ### end Alembic commands ###
