"""delete enum in execution

Revision ID: bcec18dce428
Revises: b71fe18a1499
Create Date: 2023-10-22 10:11:11.049878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcec18dce428'
down_revision = 'b71fe18a1499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'help_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('help_type', postgresql.ENUM('DEPENDENT', 'INDEPENDENT', name='typehelpexecution'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
