"""delete execution

Revision ID: c4881f1444c2
Revises: d7f084c8136d
Create Date: 2023-12-27 02:54:40.410181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4881f1444c2'
down_revision = 'd7f084c8136d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('schedule_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('procedure_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('trie', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('help_type', postgresql.ENUM('DEPENDENT', 'INDEPENDENT', name='helptypeexecution'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='executions_procedure_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name='executions_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='executions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='executions_pkey')
    )
    # ### end Alembic commands ###
