"""create enum help in execution

Revision ID: d89b70bbecea
Revises: bcec18dce428
Create Date: 2023-10-22 10:26:58.514733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd89b70bbecea'
down_revision = 'bcec18dce428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    helptypeexecution_enum = postgresql.ENUM('DEPENDENT', 'INDEPENDENT', name='helptypeexecution', create_type=False)
    helptypeexecution_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('executions', sa.Column('help_type', helptypeexecution_enum, nullable=True))
    
    
    # op.add_column('executions', sa.Column('help_type', sa.Enum('DEPENDENT', 'INDEPENDENT', name='helptypeexecution'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'help_type')
    # ### end Alembic commands ###
