"""finance fields

Revision ID: df400511f8e2
Revises: 10aa361360ce
Create Date: 2025-03-09 00:32:52.612178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df400511f8e2'
down_revision = '10aa361360ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor_payment_details', sa.Column('bank_branch', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('status', sa.Enum('NOT_FOUND', 'CANCELED', 'NOT_AUTHORIZED', 'INVALID_REQUEST', 'COMPANY_NOT_QUALIFIED', 'CERTIFICATE_EXPIRED', 'AUTHORIZED', 'IN_PROCESS', name='invoiceenum'), nullable=False))
    op.add_column('invoices', sa.Column('api_status', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'api_status')
    op.drop_column('invoices', 'status')
    op.drop_column('instructor_payment_details', 'bank_branch')
    # ### end Alembic commands ###
