"""invoice table refresh

Revision ID: e98f8c0bd129
Revises: df400511f8e2
Create Date: 2025-03-09 14:08:40.153181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e98f8c0bd129'
down_revision = 'df400511f8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    statustype_enum = postgresql.ENUM('SENDER', 'CANCELED', name='invoicesenderstatusenum', create_type=False)
    statustype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('invoices', sa.Column('sender_status', statustype_enum, nullable=True))

    # op.add_column('invoices', sa.Column('sender_status', sa.Enum('SENDER', 'CANCELED', name='invoicesenderstatusenum'), nullable=True))
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', postgresql.ENUM('NOT_FOUND', 'CANCELED', 'NOT_AUTHORIZED', 'INVALID_REQUEST', 'COMPANY_NOT_QUALIFIED', 'CERTIFICATE_EXPIRED', 'AUTHORIZED', 'IN_PROCESS', name='invoiceenum'), autoincrement=False, nullable=False))
    op.drop_column('invoices', 'sender_status')
    # ### end Alembic commands ###
