"""table scheduled refresh

Revision ID: f4bcce4d52c5
Revises: 6329cbf5f6f9
Create Date: 2023-09-20 10:08:29.491357

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'f4bcce4d52c5'
down_revision = '6329cbf5f6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('event_begin', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('event_finish', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('event_user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.create_foreign_key(None, 'schedules', 'users', ['event_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'event_user_id')
    op.drop_column('schedules', 'event_finish')
    op.drop_column('schedules', 'event_begin')
    # ### end Alembic commands ###
