"""event_id implements

Revision ID: f96228a0f9e0
Revises: 8f0b23f56628
Create Date: 2024-01-21 20:12:58.707857

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f96228a0f9e0'
down_revision = '8f0b23f56628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('event_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'event_id')
    # ### end Alembic commands ###
