"""user profiles

Revision ID: ff98aa5609a3
Revises: 1fe8bf9dfa78
Create Date: 2025-01-21 18:01:19.537668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff98aa5609a3'
down_revision = '1fe8bf9dfa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userpermission ADD VALUE 'OWER'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute("""
        CREATE TYPE userpermission AS ENUM('ADMIN', 'INSTRUCTOR', 'PARENTS');
        ALTER TABLE users ALTER COLUMN permission TYPE userpermission USING permission::text::userpermission;
        DROP TYPE userpermission;
        ALTER TYPE userpermission_new RENAME TO userpermission;
    """)
    # ### end Alembic commands ###
