"""f...

Revision ID: ffaff8dcf4f1
Revises: bc54e8823b15
Create Date: 2023-08-27 16:33:35.405907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaff8dcf4f1'
down_revision = 'bc54e8823b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedules_skill_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_skill_id_fkey', 'schedules', 'students', ['skill_id'], ['id'])
    # ### end Alembic commands ###
